name: Python Workflow
on:
  push:
    branches:
      - main  # Change this to your branch name if necessary
  pull_request:
    branches:
      - main  # Change this to your branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest  # Change the runner if needed

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace "x" with the desired Python version

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ezflow_deploy
        repository: ezactivevn/ezleague
        token: ${{ secrets.PAT_TOKEN }}


    - name: 
      run: cd ..  # Change this to your folder name if necessary

    - name: list files
      run: ls -a

    - name: Run Python script
      run:  python runscript.py

    - name: list client
      run: ls client
