name: Python Workflow
on:
  push:
    branches:
      - main  # Change this to your branch name if necessary
  pull_request:
    branches:
      - main  # Change this to your branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest  # Change the runner if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: ezactivevn/ezleague
        token: ${{ secrets.PAT_TOKEN }}

    - name: list files
      run: ls -R

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace "x" with the desired Python version

    - name: Run Python script
      run: cd .. 
          python runscript.py  # Replace "your_script.py" with the name of your Python script
