name: Python Workflow
on:
  # dispatch
  workflow_dispatch: # Manually trigger the workflow
    inputs:
      app_name:
        description: 'Application name'
        required: true
        default: 'unknown'

  


jobs:
  build:
    runs-on: ubuntu-latest  # Change the runner if needed

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace "x" with the desired Python version
    - name: Checkout code
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ezleague_demo
        repository: ezactivevn/ezleague
        token: ${{ secrets.PAT_TOKEN }}

    - name: add GOOGLE_APPLICATION_CREDENTIALS 
      run: export GOOGLE_APPLICATION_CREDENTIALS=client_secret.json

    - name: log GOOGLE_APPLICATION_CREDENTIALS 
      run: echo $GOOGLE_APPLICATION_CREDENTIALS

    - name: 
      run: cd ..  # Change this to your folder name if necessary

    - name: list files
      run: ls -a

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install firebase-admin
        pip install mysql-connector-python
    
    - name: Run Python script
      run:  python runscript.py ${{ github.event.inputs.app_name }}
      id: site_id

    - name: list client
      run: ls client
