name: Python Workflow
on:
  push:
    branches:
      - main  # Change this to your branch name if necessary
  pull_request:
    branches:
      - main  # Change this to your branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest  # Change the runner if needed

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace "x" with the desired Python version
    - name: Checkout code
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ezflow_deploy
        repository: ezactivevn/ezleague
        token: ${{ secrets.PAT_TOKEN }}


    - name: 
      run: cd ..  # Change this to your folder name if necessary

    - name: list files
      run: ls -a

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python script
      run:  python runscript.py ezleague23  # Change this to your script name if necessary

    - name: list client
      run: ls client

  deploy_firebase:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ezflow_deploy
          repository: ezactivevn/ezleague
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install Firebase CLI
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only site --token ${{ secrets.FIREBASE_TOKEN }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

