name: Python Workflow
on:
  push:
    branches:
      - main  # Change this to your branch name if necessary
  pull_request:
    branches:
      - main  # Change this to your branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest  # Change the runner if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check Github User
      run: |
        git --version
        git config user.name 'Phu Hoang'
        git config user.email 'mchoang98@gmail.com'
        git config user.name
        git config user.email
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace "x" with the desired Python version

    - name: Run Python script
      run: python runscript.py  # Replace "your_script.py" with the name of your Python script
