name: Clone Repository

on:
  push:
    branches:
      - main

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ezactivevn/ezleague
          token: ${{ secrets.PAT_TOKEN }}  # Replace with the name of your secret
          branch: develop

      - name: run script
        run: |
          cd ezleague
          npm install
          npm run build
          npm run start





