name: Deploy Android App

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version'
        required: true
      app_name:
        description: 'App Name'
        required: true
      repository_url:
        description: 'Repository URL'
        required: true
      branch:
        description: 'Branch'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
          repository: ${{ github.event.inputs.repository_url }}
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Install Fastlane
        run: gem install fastlane -N

      - name: Install dependencies
        run: cd client && npm install --legacy-peer-deps
      
      - name: Remove Android SDK
        run: cd client && rm -rf android
      
      - name: Build Android
        run: cd client && npx cap add android

      - name: Generate resources
        run: cd client && npx capacitor-assets generate

      - name: Set up Android SDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Make gradlew executable
        run: cd client && cd android && chmod +x ./gradlew

      - name: Build Android with Fastlane
        run: |
          cd client
          fastlane build_android_internal_testing version:${{ github.event.inputs.release_version }} app_name:${{ github.event.inputs.app_name }}
        env:
          FASTLANE_GRADLE_HOME: ${{ github.workspace }}/client/android/gradle/wrapper
          APP_VERSION: ${{ github.event.inputs.release_version }}
          APP_NAME: ${{ github.event.inputs.app_name }}
          TRACK: "internal"


