name: Deploy IOS

on:
  workflow_dispatch: # Manually trigger the workflow
    inputs:
      app_identifier:
        description: 'App Identifier'
        required: true
        default: 'com.example.app'
      team_id:
        description: 'Team ID'
        required: true
        default: 'XXXXXXXXXX'
      apple_id:
        description: 'Apple ID'
        required: true
        default: 'app'
      app_name:
        description: 'App Name'
        required: true
        default: 'new_app'
      repository:
        description: 'Repository'
        required: true
        default: 'app'
      branch:
        description: 'Branch'
        required: true
        default: 'main'

jobs:
  deploy_ios:
    runs-on: macOS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
          repository: ${{ github.event.inputs.repository }}
          token: ${{ secrets.PAT_TOKEN }}

      # - name: Install capacitor
      #   run: npm install -g @capacitor/cli

      - name: Install dependencies
        run: cd client && npm install --legacy-peer-deps

      - name: Remove iOS
        run: rm -rf client/ios

      - name: Build IOS
        run: cd client && npx cap add ios

      - name: Generate resources
        run: cd client && npx capacitor-assets generate

      # - name: Setup Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: 2.7

      # - name: Cache Ruby gems
      #   uses: actions/cache@v2
      #   with:
      #     path: vendor/bundle

      # - name: Install CocoaPods
      #   run: gem install cocoapods

      # - name: Cache CocoaPods dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: client/ios/App/Pods

      # - name: Install Fastlane
      #   run: gem install fastlane -NV
      
      - name: Run pod install
        run: cd client/ios/App && pod install

      - name: Copy files to iOS
        run: |
          # Create directories recursively
          mkdir -p client/ios/App/certs
          mkdir -p client/ios/App/fastlane

          # Copy files
          cp client/backup/certs/Certificates.cer client/ios/App/certs/Certificates.cer
          cp client/backup/fastlane/Fastfile client/ios/App/fastlane/Fastfile
          cp client/backup/api_key.json client/ios/App/api_key.json

      - name: Deploy IOS
        env:
          APP_IDENTIFIER: ${{ github.event.inputs.app_identifier }}
          TEAM_ID: ${{ github.event.inputs.team_id }}
          APP_NAME: ${{ github.event.inputs.app_name }}
          APPLE_ID: ${{ github.event.inputs.apple_id }}
          KEYCHAINPASSWORD: ${{ secrets.KEYCHAINPASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          cd client/ios/App
          fastlane ios release_app
          fastlane ios deploy_to_testflight
