
name: Clone Workflow


on:
  workflow_dispatch:
    inputs:
      github_token:
        description: 'GitHub Token'
        required: true

extends:
  - .github/workflows/base.yml


jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ezactivevn/ezleague
          token: ${{ secrets.PAT_TOKEN }}  # Replace with the name of your secret
          path: ezleague
          ref: develop

      - name: List files
        run: ls -R ezleague
    





