name: Cronjob delete sites in firebase

on: 
  schedule:
    - cron: "0 0 * * *"  # Run every day at 00:00

jobs:
  delete:
    runs-on: self-hosted

    steps:
        # checkout self
    - name: Checkout code 
      uses: actions/checkout@v2
      with:
        ref: main
        token: ${{ secrets.PAT_TOKEN }}
 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace "x" with the desired Python version
            
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  


    - name: Delete firebase hostings
      run: python firebase.py

