name: Delete Project

on:
  workflow_dispatch:
    inputs:
      app_id:
        description: 'Application ID'
        required: true
      email:
        description: 'Customer Email'
        required: true
      requester:
        description: 'Requester Email'
        required: true

jobs:
  delete:
    runs-on: self-hosted

    steps:
        # checkout self
    - name: Checkout code 
      uses: actions/checkout@v2
      with:
        ref: main
        token: ${{ secrets.PAT_TOKEN }}
 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace "x" with the desired Python version
            
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install mysql-connector-python
        pip install pusher
        pip install google-auth


    - name: Delete Project
      run: python delete.py ${{ github.event.inputs.app_id }} ${{ secrets.GCLOUD_PASSWORD }} ${{ github.event.inputs.email }} ${{ github.event.inputs.requester }}
      env:
          APP_ID: ${{ github.event.inputs.app_id }}
          GCLOUD_PASSWORD: ${{ secrets.GCLOUD_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          

