name : Delete Project 
on:
    workflow_dispatch:
        inputs:
            app_id:
                description: 'Application ID'
                required: true

jobs:
    delete:
        runs-on: self-hosted

        steps:
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
                python-version: 3.x  # Replace "x" with the desired Python version
            
        - name: Install dependencies
          run: |
                python -m pip install --upgrade pip
                pip install requests
                pip install mysql-connector-python

        - name: Delete Project
          run: python delete_project.py ${{ github.event.inputs.app_id }} ${{secrets.GCLOUD_PASSWORD}}

            
                
            

           
