name: Server Workflow
on:
  # dispatch
  workflow_dispatch: # Manually trigger the workflow
    inputs:
      app_name:
        description: 'App Name'
        required: true
        default: 'unknown'
      repo_url:
        description: 'Repository URL'
        required: true
        default: 'unknown'


jobs:
  build:
    runs-on: self-hosted

    steps:
   
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master
        repository: ${{ github.event.inputs.repo_url }}
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up Git
      run: |
        git config --global user.name ${{ vars.USERNAME }}
        git config --global user.email ${{ vars.EMAIL }}

        
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master
        repository: ${{ github.event.inputs.repo_url }}
        token: ${{ secrets.PAT_TOKEN }}
    
    - name: Authenticate with GitHub
      env:
        TOKEN: ${{ secrets.PAT_TOKEN }}
      run: echo "machine github.com login ${{vars.USERNAME}} password $TOKEN" > ~/.netrc

    - name : add PAT_TOKEN
      run: export PAT_TOKEN=${{ secrets.PAT_TOKEN }}

    - name: log PAT_TOKEN
      run: echo $PAT_TOKEN

    - name : add FIREBASE_TOKEN
      run: export FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}

    - name: log FIREBASE_TOKEN
      run: echo $FIREBASE_TOKEN

    - name: add GOOGLE_APPLICATION_CREDENTIALS 
      run: export GOOGLE_APPLICATION_CREDENTIALS=client_secret.json

    - name: log GOOGLE_APPLICATION_CREDENTIALS 
      run: echo $GOOGLE_APPLICATION_CREDENTIALS


    - name: list files
      run: ls -a

    - name: login as root
      run: echo ${{ secrets.GCLOUD_PASSWORD }} | sudo -S su

    - name: Remove folder server
      run: echo ${{ secrets.GCLOUD_PASSWORD }} | sudo -S rm -rf /var/www/html/${{ github.event.inputs.app_name }}

    - name: Copy folder server to /var/www/html/
      run: echo ${{ secrets.GCLOUD_PASSWORD }} | sudo -S cp -r server /var/www/html/${{ github.event.inputs.app_name }}

    - name: Change owner of /var/www/html/
      run: echo ${{ secrets.GCLOUD_PASSWORD }} | sudo -S chown -R www-data:www-data /var/www/html/${{ github.event.inputs.app_name }}

    - name: Change permission of /var/www/html/
      run: echo ${{ secrets.GCLOUD_PASSWORD }} | sudo -S chmod -R 755 /var/www/html/${{ github.event.inputs.app_name }}

    - name: Change directory to /var/www/html/
      run: cd /var/www/html/${{ github.event.inputs.app_name }}

    - name: Install dependencies
      run: composer install --ignore-platform-reqs

        




