name: Server Workflow

on:
  workflow_dispatch:
    inputs:
      app_id:
        description: 'Application ID'
        required: true
        default: 'unknown'
      site_id:
        description: 'Site ID'
        required: true
      test_data:
        description: 'Test data'
        required: true
      app_password:
        description: 'User Login Password'
        required: true

jobs:
  build:
    runs-on: self-hosted

    env:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      GOOGLE_APPLICATION_CREDENTIALS: client_secret.json
      GCLOUD_PASSWORD: ${{ secrets.GCLOUD_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      USERNAME: ${{ vars.USERNAME }}
      EMAIL: ${{ vars.EMAIL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main 

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Set up Git
        run: |
          git config --global user.name $USERNAME
          git config --global user.email $EMAIL

      - name: Remove existing app folder
        run: echo ${{ secrets.GCLOUD_PASSWORD }} | sudo -S rm -rf /var/www/html/${{ github.event.inputs.app_id }}

      - name: Run auto.py
        run: python3 auto.py
        env: 
          APP_ID: ${{ github.event.inputs.app_id }}
          GCLOUD_PASSWORD: ${{ secrets.GCLOUD_PASSWORD }}
          TEST_DATA: ${{ github.event.inputs.test_data }}
          SITE_ID: ${{ github.event.inputs.site_id }}

      - name: Set up environment variables
        run: |
          echo "PAT_TOKEN=${{ secrets.PAT_TOKEN }}" >> $GITHUB_ENV
          echo "FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}" >> $GITHUB_ENV
          echo "GOOGLE_APPLICATION_CREDENTIALS=client_secret.json" >> $GITHUB_ENV

      - name: List current directory
        run: ls -l

      - name: Run createDB.py
        run: cd /var/www/html/${{ github.event.inputs.app_id }} && python3 createDB.py ${{ github.event.inputs.app_id }} ${{ secrets.GCLOUD_PASSWORD }}
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Run settings.py
        run: cd /var/www/html/${{ github.event.inputs.app_id }} && python3 settings.py ${{ github.event.inputs.app_id }}
        env:
          APP_ID: ${{ github.event.inputs.app_id }}
          GCLOUD_PASSWORD: ${{ secrets.GCLOUD_PASSWORD }}
          TEST_DATA: ${{ github.event.inputs.test_data }}

      - name: Run setup_server.py
        run: cd /var/www/html/${{ github.event.inputs.app_id }} && python3 setup_server.py
        env:
          APP_ID: ${{ github.event.inputs.app_id }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Run updateDB.py
        run: cd /var/www/html/${{ github.event.inputs.app_id }} && python3 updateDB.py ${{ github.event.inputs.app_id }} ${{ secrets.GCLOUD_PASSWORD }}
        env:
          APP_PASSWORD: ${{ github.event.inputs.app_password }}

  notify-on-failure:
    runs-on: ubuntu-latest
    needs: build
    if: failure()

    steps:
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install requests mysql-connector-python pusher

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run sendmail.py
        run: python3 sendmail.py ${{ github.event.inputs.app_id }} 3
